# Generated by Django 4.2.2 on 2023-09-15 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='bday',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=170),
        ),
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, max_length=6),
        ),
        migrations.AddField(
            model_name='profile',
            name='is_author',
            field=models.BooleanField(default=False),
        ),
    ]
